### Home page
GET http://localhost:8000

### Get Professional
GET http://localhost:8000/professional

### Create Contact
POST http://localhost:8000/contact
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}

### Get All Contacts
GET http://localhost:8000/contact

### Get Contact by ID
GET http://localhost:8000/contact/

### Update Contact
PUT http://localhost:8000/contact/686782dbbd2fd7e7663f6257
Content-Type: application/json

{ 
"firstName":"Jane",
"lastName":"Smith",
"email":"jane.smith@example.com",
"favoriteColor":"Green",
"birthday":"1985-03-22"
}

### Delete Contact
DELETE http://localhost:8000/contact/
